### ISSUE TITLE
WHen clicking on Train Image I am getting an error.

### ISSUE THREAD

**Issue by pepabhi** [Pragya9ps/Face-Recognition-Attendance-System#1]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Downloads\Face-Recognition-Attendance-System-main\Face-Recognition-Attendance-System-main\AMS_Run.py", line 627, in trainimg
    recognizer = cv2.face.LBPHFaceRecognizer_create()
                 ^^^^^^^^
AttributeError: module 'cv2' has no attribute 'face'

**Comment by appucharan21** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "F:\Project\Face-Recognition-Attendance-System-main\Face-Recognition-Attendance-System-main\AMS_Run.py", line 627, in trainimg
    recognizer = cv2.face.LBPHFaceRecognizer_create()
                 ^^^^^^^^
Attribute Error: module 'cv2' has no attribute 'face'

pls help me to solve this problem
