### ISSUE TITLE
when i click train image there is error

### ISSUE THREAD

**Issue by appucharan21** [Pragya9ps/Face-Recognition-Attendance-System#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "F:\Project\Face-Recognition-Attendance-System-main\Face-Recognition-Attendance-System-main\AMS_Run.py", line 627, in trainimg
    recognizer = cv2.face.LBPHFaceRecognizer_create()
                 ^^^^^^^^
AttributeError: module 'cv2' has no attribute 'face'

 pls help me to solve this problem

**Comment by innovatorved** [comment]
Here is the corrected version of the text:

To solve the error, you can try the following steps in your command prompt or terminal:

```bash
pip install --upgrade pip
pip install --force-reinstall opencv-contrib-python
pip install --no-cache --force-reinstall opencv-contrib-python
```

If the error persists, you can try restarting your computer.

**Comment by innovatorved** [comment]
@Pragya9ps 

> Creating a repository is not enough. We must address any underlying issues.

**Comment by appucharan21** [comment]
what will be the Front end tool and back end tool using in this?

**Comment by appucharan21** [comment]
> 

Traceback (most recent call last):
  File "D:\FRBAS\testing.py", line 4, in <module>
    recognizer = cv2.createLBPHFaceRecognizer()
AttributeError: module 'cv2' has no attribute 'createLBPHFaceRecognizer'

pls help me to slove this problem

**Comment by ihu5** [comment]
> > 
> 
> Traceback (most recent call last): File "D:\FRBAS\testing.py", line 4, in recognizer = cv2.createLBPHFaceRecognizer() AttributeError: module 'cv2' has no attribute 'createLBPHFaceRecognizer'
> 
> pls help me to slove this problem

python -m pip install --user opencv-contrib-python

**Comment by co-de-er123** [comment]
Hey there i am getting this error while training images
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Hp\Downloads\Face-Recognition-Attendance-System-main\Face-Recognition-Attendance-System-main\AMS_Run.py", line 627, in trainimg
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2' has no attribute 'face'

I tried the above given methods and none of them seem to work any other fixes available please let me know
